GET http://localhost:1234
Content-Type: application/json

{
    "api": "CBuW$66aWU!MbZ41h^JH^nLAw%^^sh%JfJmp82#ud*YX91Fx5N6%t6%!udFF"
}

###
GET http://localhost:1234/user
Content-Type: application/json


{
    "api": "CBuW$66aWU!MbZ41h^JH^nLAw%^^sh%JfJmp82#ud*YX91Fx5N6%t6%!udFF",
    "user": "12345",
    "pass": "12345"
}

###
POST http://localhost:1234/post
Content-Type: application/json

{
    "api": "CBuW$66aWU!MbZ41h^JH^nLAw%^^sh%JfJmp82#ud*YX91Fx5N6%t6%!udFF",
    "titulo": "gfdg",
    "mensaje": "fdf",
    "imagen": "dsfsdf",
    "adjunto": "dfdf"
}

###
POST http://localhost:1234/update
Content-Type: application/json

{
    "api": "CBuW$66aWU!MbZ41h^JH^nLAw%^^sh%JfJmp82#ud*YX91Fx5N6%t6%!udFF",
    "titulo": "hoy es jueves",
    "mensaje": "fdf",
    "imagen": " dsfsdf",
    "adjunto": "dfdf",
    "id": 14
}

###
POST http://localhost:1234/updateUser
Content-Type: application/json

{
    "api": "CBuW$66aWU!MbZ41h^JH^nLAw%^^sh%JfJmp82#ud*YX91Fx5N6%t6%!udFF",
    "newUser": "12345",
    "newPass": "12345"
}

###
DELETE http://localhost:1234/delete?id=14
Content-Type: application/json

{
    "api": "CBuW$66aWU!MbZ41h^JH^nLAw%^^sh%JfJmp82#ud*YX91Fx5N6%t6%!udFF"
}
